services:
  # Keycloak for SSO
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - home-automation-network

  # Keycloak Database
  keycloak-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - home-automation-network

  # Home Automation Database
  home-automation-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=home_automation
      - POSTGRES_USER=homeuser
      - POSTGRES_PASSWORD=homepass
    volumes:
      - home_automation_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - home-automation-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - home-automation-network

  # MQTT Broker (EMQX)
  mqtt-broker:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_logs:/opt/emqx/log
    networks:
      - home-automation-network

volumes:
  keycloak_db_data:
  home_automation_db_data:
  redis_data:
  emqx_data:
  emqx_logs:

networks:
  home-automation-network:
    driver: bridge